### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by chenchouchou123** [iballester/SPiKE#1]
Hi @iballester , thanks for sharing this work, it looks wonderful!

Could you share with me the specific time that you would open-source this project? Thanks!!

**Comment by iballester** [comment]
Hi @chenchouchou123! Thanks for your interest and your nice comment! 
I'll be releasing the code next month, I'll drop you a comment here when it's out!

**Comment by amal-k-ajay** [comment]
Hi @iballester ,

I found your work really interesting. I'm doing my master thesis on something similar and I'm looking forward to the code release.

**Comment by iballester** [comment]
Hi @amal-k-ajay,

Thanks for your interest! I’ve been busier than expected this past month, so I won’t be able to release it until December. Apologies for the inconvenience, and thanks for your patience!

**Comment by iballester** [comment]
@amal-k-ajay @chenchouchou123 We've released the code :)

**Comment by iballester** [comment]
@amal-k-ajay @chenchouchou123 We've released the code :)

**Comment by amal-k-ajay** [comment]
Thank you!
