### ISSUE TITLE
ITOP class does not work with original file data

### ISSUE THREAD

**Issue by pr3ss** [iballester/SPiKE#2]
Could you update the code to support the original ITOP h5 file format for point cloud, or provide a brief guide on how to structure the data to make it compatible with the code?

**Comment by AlessandroSciarrillo** [comment]
It would be very useful also for me to have this code. Please upload it if you can!

**Comment by iballester** [comment]
Hi, thanks for your interest in our work! I've uploaded the script (`utils/preprocess_itop.py`) we used to preprocess the ITOP dataset to convert the .h5 files to .npz to make them compatible with the released code.
