### ISSUE TITLE
Depth threshold selection method

### ISSUE THREAD

**Issue by AlessandroSciarrillo** [iballester/SPiKE#3]
How do you determine the depth threshold used to isolate the human body? Have you implemented any code that allows for dynamic selection of this threshold? If so, could you share it? Thank you!

**Comment by iballester** [comment]
Hi, thanks again for your interest! You can see in the script I recently uploaded (`utils/preprocess_itop.py`) how we preprocessed the ITOP dataset to isolate the points belonging to the human body.

If you're looking for a more general solution, I'd suggest you have a look at https://github.com/human-3d/Human3D where they propose a work to segment human instances in 3D scenes.
